server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Essential for Angular routing
    }

    # This is how Nginx knows to talk to your API container
    location /api/ {
        # Replace this with the ACTUAL URL Render gave your API service
        # It usually looks like bazaar-api.onrender.com
        proxy_pass https://bazaar-api-v1.onrender.com; 
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}