server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; # Essential for Angular routing
    }

    # This is how Nginx knows to talk to your API container
    location /api/ {
        proxy_pass http://bazaar-api:3000/;
    }
}